services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: swiftlogistics-postgres
    environment:
      POSTGRES_DB: swiftlogistics
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: "--auth-host=trust --auth-local=trust"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - swiftlogistics-network

  # RabbitMQ Message Broker
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: swiftlogistics-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - swiftlogistics-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: swiftlogistics-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - swiftlogistics-network

  # Mock CMS System (SOAP Service)
  mock-cms:
    image: mockserver/mockserver:5.15.0
    container_name: swiftlogistics-mock-cms
    ports:
      - "8081:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/cms-expectations.json
    volumes:
      - ./mock-services/cms-expectations.json:/config/cms-expectations.json
    networks:
      - swiftlogistics-network

  # Mock ROS System (REST Service)
  mock-ros:
    image: mockserver/mockserver:5.15.0
    container_name: swiftlogistics-mock-ros
    ports:
      - "8082:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/ros-expectations.json
    volumes:
      - ./mock-services/ros-expectations.json:/config/ros-expectations.json
    networks:
      - swiftlogistics-network

  # Mock WMS System (Simple HTTP Service)
  mock-wms:
    image: nginx:alpine
    container_name: swiftlogistics-mock-wms
    ports:
      - "8083:80"
    volumes:
      - ./mock-services/wms.html:/usr/share/nginx/html/index.html
    networks:
      - swiftlogistics-network

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  swiftlogistics-network:
    driver: bridge
